### ISSUE TITLE
Duplicate executables

### ISSUE THREAD

**Issue by ModProg** [Kl4rry/executable-finder#3]
I see too cases:

1. a path appears multiple times on the `$PATH` env variable (could be through sym links)
2. one executable is supposed to override another one

I'm unsure how this should be dealt with. In my use case, I filter them out in my code, but I was wondering if this might be a feature generally useful.

**Comment by Kl4rry** [comment]
If both name and path match for an executable it would be preferable to remove them. However if only the name match I we would  have to figure out which executable will be used when a new process is spawned. For my use case the extra cost of figuring out which executable is the real one is not worth it as I don't use the path only the name.

**Comment by Kl4rry** [comment]
But completely unique executables could be removed with a simple sort and dedup.

**Comment by ModProg** [comment]
maybe we could put this behind a feature flag or an option/separate method?

**Comment by Kl4rry** [comment]
Yeah I think a another function makes the most sense.

**Comment by Kl4rry** [comment]
Resolved by #5
